version: '3.3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      - "8080:8080"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports: 
      - "80:80"
    depends_on:
      - nodejs
